Unit_7_Coffeeshop_Product_List/Models/CoffeeShopDbContext.cs
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Unit_7_Coffeeshop_Product_List.Models;

public partial class CoffeeShopDbContext : DbContext
{
    public CoffeeShopDbContext()
    {
    }

    public CoffeeShopDbContext(DbContextOptions<CoffeeShopDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Product> Products { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Server=.\\SQLExpress;Database=CoffeeShopDb;Trusted_Connection=True;TrustServerCertificate=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Product>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Products__3213E83F37B0AB65");

            entity.Property(e => e.Id).HasColumnName("id");
            entity.Property(e => e.Category).HasMaxLength(255);
            entity.Property(e => e.Description).HasMaxLength(255);
            entity.Property(e => e.Name).HasMaxLength(255);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}

Unit_7_Coffeeshop_Product_List/Models/ErrorViewModel.cs
namespace Unit_7_Coffeeshop_Product_List.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Unit_7_Coffeeshop_Product_List/Models/Product.cs
using System;
using System.Collections.Generic;

namespace Unit_7_Coffeeshop_Product_List.Models;

public partial class Product
{
    public int Id { get; set; }

    public string? Name { get; set; }

    public string? Description { get; set; }

    public double? Price { get; set; }

    public string? Category { get; set; }
}

Unit_7_Coffeeshop_Product_List/Controllers/CoffeeShopController.cs
using Microsoft.AspNetCore.Mvc;
using Unit_7_Coffeeshop_Product_List.Models;

namespace Unit_7_Coffeeshop_Product_List.Controllers
{
    public class CoffeeShopController : Controller
    {
        private readonly CoffeeShopDbContext _coffeeDbContext;
        public CoffeeShopController(CoffeeShopDbContext context)
        {
            _coffeeDbContext = context;
        }
        public IActionResult Index()
        {
            List<Product> result = _coffeeDbContext.Products.ToList();
            return View(result);
        }
        public IActionResult ViewProduct(int ProductId)
        {
            Product p = _coffeeDbContext.Products.FirstOrDefault(p => p.Id == ProductId);
            return View(p);
        }
        public IActionResult AddProduct(Product p)
        {
            _coffeeDbContext.Products.Add(p);
            _coffeeDbContext.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult DeleteProduct(int[] DeleteList)
        {
            foreach (int ProductId in DeleteList)
            {
                Product p = _coffeeDbContext.Products.FirstOrDefault(p => p.Id == ProductId);
                _coffeeDbContext.Products.Remove(p);
            }
            _coffeeDbContext.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Unit_7_Coffeeshop_Product_List/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Unit_7_Coffeeshop_Product_List.Models;

namespace Unit_7_Coffeeshop_Product_List.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Unit_7_Coffeeshop_Product_List/Views/CoffeeShop/Index.cshtml
@model List<Product>
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>All products at this coffeeshop (click to learn more)</h1>

<form asp-method="post" asp-action="DeleteProduct">
    @foreach (Product p in @Model)
    {
        <div>
            <label for="@p.Id">
                <a asp-action="ViewProduct" asp-route-ProductId="@p.Id">@p.Name</a>
            </label>
            <input type="checkbox" name="DeleteList[]" id="@p.Id" value="@p.Id" />
        </div>
    }
    <button type="submit">Delete Product</button>
</form>

<br />
<br />
<h2>Add product</h2>
<form asp-method="post" asp-action="AddProduct">
    <p>Enter the name: <input type="text" name="Name" /></p>
    <p>Enter the description: <input type="text" name="Description" /></p>
    <p>Enter the price: <input type="number" step=".01" name="Price" /></p>
    <label>Select the category</label>
    <select name="Category" id="Category">
        <option value="Beverage">Beverage</option>
        <option value="Food">Food</option>
    </select>
    <br />
    <br />
    <button type="submit">Add Product</button>
</form>

Unit_7_Coffeeshop_Product_List/Views/CoffeeShop/ViewProduct.cshtml
@model Product
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>@Model.Name details</h1>
<p>Price: @Model.Price</p>
<p>Description: @Model.Description</p>
<p>Category: @Model.Category</p>
<br />
<a asp-controller="CoffeeShop" asp-action="Index">Return</a>

Unit_7_Coffeeshop_Product_List/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to DanTheMan's Coffee Shop!</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Unit_7_Coffeeshop_Product_List/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Unit_7_Coffeeshop_Product_List</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Unit_7_Coffeeshop_Product_List.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Unit_7_Coffeeshop_Product_List</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CoffeeShop" asp-action="Index">Products</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Unit_7_Coffeeshop_Product_List - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>